---
- name: Loading Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.43.0/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
    mode: "0755"

- name: Unboxing Vector
  ansible.builtin.unarchive:
    src: "/tmp/vector-0.43.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/opt/"
    remote_src: true

- name: Create configuration
  ansible.builtin.file:
    path: "/etc/vector/"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0755"
    
- name: Copy template
  ansible.builtin.template:
    src: "./templates/vector_config.yml.j2"
    dest: "/etc/vector/vector.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Vector

- name: Configure Vector
  ansible.builtin.command: /opt/vector-x86_64-unknown-linux-gnu/bin/vector --config /etc/vector/vector.conf
  async: 30
  poll: 0
  notify: Restart Vector

- name: Ensure Vector service is running
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: true
